version: "3.3"
# Servidor nginx
services:
  web:
    image: nginx:latest
    ports:
      - "8081:80"
    volumes:
      - ./site-php/:/var/www/html
      - ./site-php/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm1
  web-insecure:
    image: nginx:latest
    ports:
      - "8082:80"
    volumes:
      - ./site-php-insecure/:/var/www/html
      - ./site-php-insecure/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm2
  store-data:
    image: nginx:latest
    ports:
      - "8083:80"
    volumes:
      - ./store-data/:/var/www/html
      - ./store-data/default.conf:/etc/nginx/conf.d/default.conf
    links:
      - php-fpm3

  # Configuración de php-fpm
  php-fpm1:
    image: php:8-fpm
    volumes:
      - ./site-php/:/var/www/html
  php-fpm2:
    image: php:8-fpm
    volumes:
      - ./site-php-insecure/:/var/www/html
  php-fpm3:
    image: php:8-fpm
    volumes:
      - ./store-data/:/var/www/html